version: '3.1'

services:

  api:
    image: ${DOCKER_REGISTRY}/${DOCKER_APP_NAME}:${IMAGE_TAG}

    container_name: ${DOCKER_APP_NAME}-green

    environment:
      - LANG=ko_KR.UTF-8
      - UWSGI_PORT=8000

    ports:
      - '8080:8000'