name: release ci/cd

on:
  push:
    branches:
      - 'release'
  pull_request:
    branches:
      - 'main'
      - 'release'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      ## 1-1 application.properties 파일 생성
      - name: make application.properties
        run: |
          mkdir -p ./src/main/resources
          cd ./src/main/resources
          touch ./application.properties
          echo "${{ secrets.PROPERTIES }}" >> ./application.properties
        shell: bash

      ## 2 스프링 프로젝트 jar 파일 빌드
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      ## 3 Docker Hub에 이미지 push
      - name: Docker build
        run: |
          docker build -t daengtionary .
          docker tag daengtionary ${{ secrets.DOCKER_HUB_USERNAME }}/daengtionary:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/daengtionary:latest
      ## 4 이미지를 서버에서 run
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/daengtionary:latest
            docker stop daeng
            docker run -d --rm --name daeng -p 80:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/daengtionary

