name: release ci/cd

on:
  push:
    branches:
      - 'release'
  pull_request:
    branches:
      - 'release'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      ## 1-1 application.properties 파일 생성
      - name: make application.properties
        run: |
          mkdir -p ./src/main/resources
          cd ./src/main/resources
          touch ./application.properties
          echo "${{ secrets.PROPERTIES }}" >> ./application.properties
        shell: bash

      ## 2 스프링 프로젝트 jar 파일 빌드
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build


      ## 3 Docker Hub에 이미지 push
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker build -t test .
          docker tag test ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest

      ## 4 이미지를 서버에서 run
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
            docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest simplewhale
            docker stop server
            sleep 5
            docker run -d --rm --name server -p 80:8080 simplewhale
            
            

#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      - name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest